// Run: node tests/hanbit-cases-actions.test.cjs
// Uses the actual game script. DOM/storage and network AI calls are stubbed.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../hanbit.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
function fixture(){
  const el={style:{},dataset:{},value:'',insertAdjacentHTML(){},remove(){},classList:{add(){},remove(){},contains(){return false},toggle(){}},addEventListener(){},querySelectorAll(){return []},setAttribute(){},getAttribute(){return null}};
  const ctx=vm.createContext({console,setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{getElementById(){return el},querySelector(){return el},querySelectorAll(){return []},addEventListener(){},documentElement:el},window:{addEventListener(){},matchMedia(){return {matches:false,addEventListener(){}}}},navigator:{},URL,Blob,Math:Object.create(Math)});
  vm.runInContext(script.slice(0,script.indexOf('/* 시작: 화면 설정 적용')),ctx);
  const run=s=>vm.runInContext(s,ctx),obj=s=>JSON.parse(JSON.stringify(run(s)));
  run(`const calls=[],notices=[]; let chipHTML='',modalHTML='';
    addLog=()=>{};toast=s=>notices.push(s);render=()=>{};renderSides=()=>{};save=()=>{};sfx=()=>{};
    maybeIncoming=()=>{};closeModal=()=>{};apptRefresh=()=>{};renderChat=()=>{};askConfirm=async()=>true;const liveAiTurn=aiTurn;aiTurn=async(...args)=>calls.push(args);
    chip=s=>{chipHTML=s};hideChip=()=>{};modal=(title,s)=>{modalHTML=s};
    function seed(loc='site'){
      G={v:1,_relVersion:2,_clockVersion:2,_affLv:2,char:{name:'테스트',age:17,stats:{str:1,wis:1,cha:1,sur:1},traits:[]},day:1,time:'방과 후',dayStep:0,loc,steps:0,hp:12,maxhp:12,calm:6,battery:6,torch:5,cash:100,items:[],mat:{metal:0,ply:0,wire:0,keepsake:0},act:1,fragments:0,sitesDone:0,district:'music',comp:{met:false,joined:false,aff:10},rel:{},chronicle:[],site:loc==='site'?{name:'피아노 괴담 구역',pos:{x:225,y:180},depth:1,cur:'r1',rooms:[{id:'r1',name:'입구',lv:0,danger:0,visited:true,exits:['r2','r3']},{id:'r2',name:'피아노실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r3',name:'방송실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r4',name:'창고',lv:2,danger:0,visited:true,exits:['r3']}]}:null};
      busy=false;PENDING={note:'',flags:{}};migrate();syncSchedule();Math.random=()=>0.99;calls.length=notices.length=0;chipHTML=modalHTML='';
    }
    seed('campus');G.comp.met=true;getRel('유민');getRel('서연');G.comp.spot='market';G.comp.spotKey=yKey();
  `);
  return {run,obj,input:el};
}
const candidate={question:'빈 방에서 소리가 반복되는 이유는?',opening:'낡은 입구의 공기는 차갑고 조용하다.',truth:'PRIVATE_TRUTH_735 비공개 원인은 예약 재생 장치다.',conclusion:'PRIVATE_CONCLUSION_912 예약 장치가 다른 방으로 녹음을 전송했다.',room_views:['r1','r2','r3','r4'].map(room=>({room,text:'빛이 닿은 바닥과 오래된 문틀이 보인다.'})),evidence:[{id:'e1',room:'r1',text:'종이에 03:15라는 시간이 세 번 적혀 있다.',meaning:'반복되는 시간이 조사 기준이 된다.'},{id:'e2',room:'r2',text:'음원이 매번 정확히 같은 구간에서 끊긴다.',meaning:'연주보다 동일한 기록의 반복을 뒷받침한다.'},{id:'e3',room:'r3',text:'두 방 사이를 연결한 선에 같은 번호가 붙어 있다.',meaning:'소리가 이동하는 경로를 추적할 근거다.'}],verification:{room:'r3',action:'번호가 같은 선의 전송을 끊고 소리가 멎는지 확인한다',requires:['e1','e2','e3'],result:'PRIVATE_RESULT_624 전송을 끊자 반복되던 소리가 함께 멎었다.'}};
async function prepared(f){f.run("seed('site');G.secret={truth:'WORLD_SECRET_479',detail:'아직 알려지지 않은 세계의 진상'};G.site.rooms.forEach(r=>r.desc='ROOM_SECRET_381');const events=[],api=[];addLog=(type,text)=>events.push({type,text});let proposal="+JSON.stringify(candidate)+";callAI=async(sys,user)=>{api.push({sys,user});return JSON.stringify(sys.includes('독립 검토자')?{valid:true,issues:[]}:proposal)};");await f.run('ensureMystery()');f.run("aiTurn=liveAiTurn;callAI=async(sys,user)=>{api.push({sys,user});return JSON.stringify({narration:'공간에 남은 흔적을 살펴본다.',choices:[],effects:{사건진행:[{case_id:G.site.caseId,evidence:[{text:'AI가 지어낸 새로운 핵심 증거',kind:'fact',role:'narrows'}]}]}})};maybeSummarize=async()=>{};checkState=()=>{};");}
let count=0;async function test(name,fn){const f=fixture();await fn(f);count++;console.log('PASS',name)}
(async()=>{
await test('Hidden generation passes structural and independent semantic review before locking',async f=>{await prepared(f);assert.equal(f.run('G.site.mystery.status'),'ready');assert.equal(f.run('api.length'),2);assert.equal(f.run('G.evidence.length'),0);assert.equal(f.run('G.site.mystery.state.solved'),false);assert.equal(f.run('mysteryPlan().truth'),candidate.truth)});
await test('Narrator and journal do not receive the answer, unseen clues, private room memo or world secret',async f=>{await prepared(f);const prompt=f.run("buildPrompt('입구를 바라본다','')");for(const value of [candidate.truth,candidate.conclusion,candidate.verification.result,candidate.evidence[0].text,'ROOM_SECRET_381','WORLD_SECRET_479'])assert.ok(!prompt.includes(value),value);f.run('openZoneJournal()');assert.ok(!f.run('modalHTML').includes(candidate.truth));assert.ok(!f.run('modalHTML').includes(candidate.evidence[0].text));});
await test('Malformed plans are rejected before review; retry is bounded',async f=>{f.run('seed();let n=0;callAI=async()=>{n++;return JSON.stringify({question:"不完全"})}');await f.run('ensureMystery()');assert.equal(f.run('n'),2);assert.equal(f.run('G.site.mystery.status'),'pending');assert.equal(f.run('G.site.caseId||null'),null)});
await test('Bad references, inaccessible evidence, duplicates and insufficient verification are rejected',f=>{
 f.run('seed();let p='+JSON.stringify(candidate));assert.equal(f.run('validateMystery(p,G.site).length'),0);
 for(const mutation of ["p.evidence[0].room='unknown'","p.evidence[1].id='e1'","p.evidence[1].room='r1'","p.verification.requires=['e1']","p.room_views.pop()","p.verification.room='r4'"]){f.run('p='+JSON.stringify(candidate)+';'+mutation);assert.ok(f.run('validateMystery(p,G.site).length')>0,mutation)}
});
await test('Independent review rejection triggers regeneration and never prints private issues',async f=>{f.run('seed();let designs=0;let reviews=0;callAI=async(sys)=>{if(sys.includes("독립 검토자")){reviews++;return JSON.stringify({valid:reviews>1,issues:["PRIVATE_REVIEW_714 정답 유출"]})} designs++;return JSON.stringify('+JSON.stringify(candidate)+')};const events=[];addLog=(type,text)=>events.push({type,text})');await f.run('ensureMystery()');assert.equal(f.run('designs'),2);assert.equal(f.run('reviews'),2);assert.equal(f.run('G.site.mystery.status'),'ready');assert.ok(!JSON.stringify(f.obj('events')).includes('PRIVATE_REVIEW_714'));});
await test('Prepared facts stay fixed through save/load and repeat preparation consumes no AI calls',async f=>{await prepared(f);const sealed=f.run('G.site.mystery.sealed');f.run('G=JSON.parse(JSON.stringify(G));migrate();const before=api.length');await f.run('ensureMystery()');assert.equal(f.run('G.site.mystery.sealed'),sealed);assert.equal(f.run('api.length'),f.run('before'));});
await test('Tampered locked facts stop play instead of generating another answer',async f=>{await prepared(f);f.run('G.site.mystery.sealed+=" ";const before=api.length');await f.run('ensureMystery()');assert.equal(f.run('api.length'),f.run('before'));assert.equal(f.run('mysteryPlan()'),null)});
await test('Preparation cannot write to a replacement game while awaiting AI',async f=>{f.run('seed();let finish;callAI=()=>new Promise(r=>finish=r)');const job=f.run('ensureMystery()');f.run('seed();finish(JSON.stringify('+JSON.stringify(candidate)+'))');await job;assert.equal(f.run('G.site.mystery||null'),null)});
await test('Concurrent preparation shares one generation and review',async f=>{f.run('seed();let callsN=0;let finish;callAI=async(sys)=>{callsN++;if(sys.includes("독립 검토자"))return JSON.stringify({valid:true});return new Promise(r=>finish=r)}');const a=f.run('ensureMystery()'),b=f.run('ensureMystery()');f.run('finish(JSON.stringify('+JSON.stringify(candidate)+'))');await Promise.all([a,b]);assert.equal(f.run('callsN'),2);});
await test('Investigation publishes only the current prepared fact and its contribution',async f=>{await prepared(f);await f.run("aiTurn('周囲를 조사한다')");assert.equal(f.run('G.site.mystery.state.found.length'),1);assert.equal(f.run('G.evidence[0].text'),candidate.evidence[0].text);const last=f.obj('api').at(-1).user;assert.ok(last.includes(candidate.evidence[0].text));assert.ok(!last.includes(candidate.evidence[1].text));assert.ok(!last.includes(candidate.truth));assert.ok(f.obj('events').some(e=>e.text.includes('사건 진행:')));});
await test('Repeated investigation reports no extra finding without inventing evidence',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");await f.run("aiTurn('입구를 다시 조사한다')");assert.equal(f.run('G.evidence.length'),1);assert.ok(f.obj('events').some(e=>e.text.includes('추가 발견 없음')));});
await test('Darkness and story-only turns cannot reveal prepared evidence',async f=>{await prepared(f);f.run('G.torch=0');await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence.length'),0);assert.ok(f.obj('events').some(e=>e.text.includes('관찰 불가')));f.run("G.torch=3;pend('',{storyOnly:true})");await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence.length'),0)});
await test('Registered investigation reveals evidence even with new display wording',async f=>{await prepared(f);f.run("dispatchGameAction(roomActionId('investigate','r1'),'소리에 집중한다')");await new Promise(r=>setImmediate(r));assert.equal(f.run('G.evidence.length'),1)});
await test('Evidence collection does not solve the case; verified action does',async f=>{await prepared(f);for(const room of ['r1','r2','r3']){f.run('G.site.cur='+JSON.stringify(room));await f.run("aiTurn('이 공간을 조사한다')");}assert.equal(f.run('G.evidence.length'),3);assert.equal(f.run('G.threads.find(t=>t.id===G.site.caseId).status'),'open');assert.equal(f.run('G.site.mystery.state.solved'),false);assert.equal(f.run('canVerifyMystery()'),true);assert.ok(f.run('gameActions().some(a=>a.id===mysteryVerifyId())'));f.run('verifyMystery()');await new Promise(r=>setImmediate(r));assert.equal(f.run('G.site.mystery.state.solved'),true);assert.equal(f.run('G.threads.find(t=>t.id===G.site.caseId).status'),'closed');assert.equal(f.run('mysteryPublic().conclusion'),candidate.conclusion)});
await test('Manual conclusion, AI case updates and legacy lore finalize cannot bypass verification',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('resolveCase(G.site.caseId,'+JSON.stringify(candidate.conclusion)+',[G.evidence[0].id],true)'),false);f.run('applyCaseUpdates([{case_id:G.site.caseId,resolution:{conclusion:'+JSON.stringify(candidate.conclusion)+',support_ids:[G.evidence[0].id]}}]);G.site.lore={recorded:false,record:"LEAK_PRIVATE_LORE_647"};finalizeZone(G.site);');assert.equal(f.run('G.site.mystery.state.solved'),false);assert.ok(!JSON.stringify(f.obj('G.lexicon')).includes('LEAK_PRIVATE_LORE_647'));});
await test('Visiting every room keeps unsolved zones resumable',async f=>{await prepared(f);f.run('G.site.rooms.forEach(r=>r.visited=true);const sealed=G.site.mystery.sealed');assert.equal(f.run('siteProg().done'),false);f.run('archiveSite()');assert.equal(f.run('G.pausedZones.length'),1);assert.equal(f.run('G.pausedZones[0].mystery.sealed'),f.run('sealed'));});
await test('Generation failure blocks investigation without consuming another clock tick',async f=>{f.run("seed();callAI=async()=>{throw new Error('NO_KEY')};const before=JSON.stringify({day:G.day,time:G.time,steps:G.steps})");await f.run('ensureMystery()');f.run("story('입구를 조사한다')");assert.equal(f.run('before'),f.run('JSON.stringify({day:G.day,time:G.time,steps:G.steps})'));assert.equal(f.run('G.evidence.length'),0);});
await test('AI outage during play still publishes the prepared fact',async f=>{await prepared(f);f.run("callAI=async()=>{throw new Error('NO_KEY')}");await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence[0].text'),candidate.evidence[0].text);assert.ok(f.obj('events').some(e=>e.type==='scene'&&e.text.includes(candidate.evidence[0].text)));});
await test('Management cannot park a fixed case or offer a misleading manual resolution',async f=>{await prepared(f);f.run('const t=G.threads.find(t=>t.id===G.site.caseId);closeThread(t.id)');assert.equal(f.run('t.status'),'open');assert.ok(!f.run('caseCard(t)').includes('결론 기록'));assert.match(f.run('caseCard(t)'),/원인 검증/)});
await test('Legacy observed records survive conversion into a fixed mystery',async f=>{f.run('seed();const t=caseRecord("기존에 조사한 질문",{scope:"local",placeId:knowledgePlace()});G.site.caseId=t.id;addCanon("이미 확인한 낡은 흔적이 남아 있다",true,true,{caseId:t.id});G.site.lore={what:"기존의 확정된 경위가 있다",fate:"폐쇄 후 버려졌다"};const original=JSON.stringify(G.evidence);callAI=async(sys)=>JSON.stringify(sys.includes("독립 검토자")?{valid:true}:'+JSON.stringify(candidate)+')');await f.run('ensureMystery()');assert.equal(f.run('JSON.stringify(G.evidence)'),f.run('original'));assert.equal(f.run('G.site.caseId'),f.run('t.id'));assert.equal(f.run('G.site.mystery.status'),'ready');});
await test('A generated ordinary zone prepares and reviews its hidden case before returning the public introduction',async f=>{
 f.run('seed();ensureAncient=async()=>{};G.ancient=[];let generation=0;callAI=async(sys)=>{if(sys.includes("독립 검토자"))return JSON.stringify({valid:true});if(sys.includes("비공개 미스터리 설계자"))return JSON.stringify('+JSON.stringify(candidate)+');generation++;return JSON.stringify({name:"음원이 반복되는 별관",theme:"OLD_PRIVATE_THEME",intro:"UNREVIEWED_INTRO",rooms:G.site.rooms})};');const intro=await f.run('genSite()');assert.equal(intro,candidate.opening);assert.equal(f.run('G.site.mystery.status'),'ready');assert.equal(f.run('generation'),1);assert.ok(!f.run("buildPrompt('조사한다','')").includes('OLD_PRIVATE_THEME'));
});
await test('Verification is unavailable before all evidence and outside the registered room',async f=>{await prepared(f);assert.equal(f.run('canVerifyMystery()'),false);for(const room of ['r1','r2','r3']){f.run('G.site.cur='+JSON.stringify(room));await f.run("aiTurn('이 공간을 조사한다')");}f.run("G.site.cur='r1'");assert.equal(f.run('canVerifyMystery()'),false);f.run('verifyMystery()');assert.equal(f.run('G.site.mystery.state.solved'),false)});
await test('Damaged progress state stops a locked case without regenerating it',async f=>{await prepared(f);f.run('delete G.site.mystery.state;const before=api.length');assert.equal(f.run('mysteryPlan()'),null);await f.run('ensureMystery()');assert.equal(f.run('api.length'),f.run('before'))});
await test('A main ward also prepares its case before exposing an introduction',async f=>{f.run('seed();G.wards=[{terrain:Object.keys(WARD_TYPES)[0],id:"testward",name:"고요한 구역",mood:"침묵",lore:"WARD_PRIVATE_SECRET"}];wardArrive=()=>{};callAI=async(sys)=>JSON.stringify(sys.includes("독립 검토자")?{valid:true}:sys.includes("비공개 미스터리 설계자")?'+JSON.stringify(candidate)+':{theme:"OLD_WARD_THEME",intro:"UNREVIEWED_WARD_INTRO",rooms:G.site.rooms});');const intro=await f.run('genBigZone({key:"testward",terrain:Object.keys(WARD_TYPES)[0],campus:G.wards[0],pos:[0,0]})');assert.equal(intro,candidate.opening);assert.equal(f.run('G.site.mystery.status'),'ready');assert.ok(!f.run("buildPrompt('조사한다','')").includes('WARD_PRIVATE_SECRET'))});
console.log(`${count} private-mystery scenario groups passed.`);
})().catch(e=>{console.error(e);process.exitCode=1});
