// Run: node tests/hanbit-cases-actions.test.cjs
// Uses the actual game script. DOM/storage and network AI calls are stubbed.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../hanbit.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
function fixture(){
  const el={style:{},dataset:{},value:'',insertAdjacentHTML(){},remove(){},classList:{add(){},remove(){},contains(){return false},toggle(){}},addEventListener(){},querySelectorAll(){return []},setAttribute(){},getAttribute(){return null}};
  const ctx=vm.createContext({console,setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{getElementById(){return el},querySelector(){return el},querySelectorAll(){return []},addEventListener(){},documentElement:el},window:{addEventListener(){},matchMedia(){return {matches:false,addEventListener(){}}}},navigator:{},URL,Blob,Math:Object.create(Math)});
  vm.runInContext(script.slice(0,script.indexOf('/* 시작: 화면 설정 적용')),ctx);
  const run=s=>vm.runInContext(s,ctx),obj=s=>JSON.parse(JSON.stringify(run(s)));
  run(`const calls=[],notices=[]; let chipHTML='',modalHTML='';
    addLog=()=>{};toast=s=>notices.push(s);render=()=>{};renderSides=()=>{};save=()=>{};sfx=()=>{};
    maybeIncoming=()=>{};closeModal=()=>{};apptRefresh=()=>{};renderChat=()=>{};askConfirm=async()=>true;const liveAiTurn=aiTurn;aiTurn=async(...args)=>calls.push(args);
    chip=s=>{chipHTML=s};hideChip=()=>{};modal=(title,s)=>{modalHTML=s};
    function seed(loc='site'){
      G={v:1,_relVersion:2,_clockVersion:2,_affLv:2,char:{name:'테스트',age:17,stats:{str:1,wis:1,cha:1,sur:1},traits:[]},day:1,time:'방과 후',dayStep:0,loc,steps:0,hp:12,maxhp:12,calm:6,battery:6,torch:5,cash:100,items:[],mat:{metal:0,ply:0,wire:0,keepsake:0},act:1,fragments:0,sitesDone:0,district:'music',comp:{met:false,joined:false,aff:10},rel:{},chronicle:[],site:loc==='site'?{name:'피아노 괴담 구역',pos:{x:225,y:180},depth:1,cur:'r1',rooms:[{id:'r1',name:'입구',lv:0,danger:0,visited:true,exits:['r2','r3']},{id:'r2',name:'피아노실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r3',name:'방송실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r4',name:'창고',lv:2,danger:0,visited:true,exits:['r3']}]}:null};
      busy=false;PENDING={note:'',flags:{}};migrate();syncSchedule();Math.random=()=>0.99;calls.length=notices.length=0;chipHTML=modalHTML='';
    }
    seed('campus');G.comp.met=true;getRel('유민');getRel('서연');G.comp.spot='market';G.comp.spotKey=yKey();
  `);
  return {run,obj,input:el};
}
function setupAI(f){f.run(`
 const events=[],api=[];addLog=(type,text)=>events.push({type,text});
 function worldDraft(){return {truth:'ROOT_SECRET_853 보존 대상은 폐기된 학적 기록이다.',detail:'ROOT_DETAIL_793 기록을 옮겨 감춘 경위가 있다.',opening:'복도에 서면 교실 문 너머에서 목소리가 들린다.',roster:'안개 기숙사와 방송 시설의 빈 칸이 남아 있다.',rumors:[HOME_REGION,HOODS.east.n,HOODS.south.n,HOODS.north.n].map(region=>({region,belief:'이곳에는 지워진 기록에 관한 엇갈린 소문이 돈다.'})),chapters:['lacuna','c0','c1'].map((key,i)=>({key,role:'담당 부분 '+i,fragment:'PRIVATE_FRAGMENT_'+key,link:'LINK_'+key+' 기록에 같은 식별자가 남아 있다.',riddle:'이 공간에서 되풀이되는 현상이 있다.',lore:'PRIVATE_LORE_'+key+' 닫힌 교실의 사연과 교칙이 있다.'}))}}
 function smallRooms(){return Array.from({length:4},(_,i)=>({id:'r'+(i+1),name:'공간 '+(i+1),danger:0,exits:i===0?['r2']:i===3?['r3']:['r'+i,'r'+(i+2)]}))}
 function caseDraft(){const d=G.site;return {question:d.name+'의 반복 현상은 왜 일어나는가?',opening:'문틀과 낡은 바닥이 조용히 빛을 받는다.',truth:'CASE_SECRET_'+d.name+'의 원인은 예약 장치다.',conclusion:'예약된 기록이 선을 통해 다른 공간으로 전달되었다.',room_views:d.rooms.map(r=>({room:r.id,text:'바닥과 벽에 오래된 흔적이 남아 있다.'})),evidence:[{id:'e1',room:'r1',text:d.name+' 입구의 시간표에는 같은 시각이 세 번 적혀 있다.',meaning:'반복 주기를 비교할 기준이다.'},{id:'e2',room:'r2',text:d.name+' 준비실의 음원은 매번 같은 구간에서 끊긴다.',meaning:'동일한 기록이 반복된다는 근거다.'},{id:'e3',room:'r3',text:d.name+' 장비실의 전송선에 같은 번호가 붙어 있다.',meaning:'음원의 이동 경로를 확인할 근거다.'}],verification:{room:'r3',action:'같은 번호의 전송선을 분리하고 소리가 멎는지 확인한다',requires:['e1','e2','e3'],result:'선을 분리하자 반복되는 소리가 함께 멎었다.'},deduction:{hypotheses:[{id:'h1',text:'빈 공간에서 새 연주가 시작된다'},{id:'h2',text:'기록된 음원이 정해진 경로로 반복 전송된다'},{id:'h3',text:'바람이 울려 소리가 반복된다'}],answer_id:'h2',supports:['e2','e3'],explanation:'같은 구간의 반복과 번호가 같은 선이 기록의 전송을 입증한다.'},...(d.big?{main_link:campaignChapter(d.key).link}:{})}}
 callAI=async(sys,user)=>{api.push({sys,user});if(sys.includes('독립 검토자'))return JSON.stringify({valid:true,issues:[]});if(sys.includes('비공개 본편 설계자'))return JSON.stringify(worldDraft());if(sys.includes('비공개 미스터리 설계자'))return JSON.stringify(caseDraft());if(sys.includes('공간 생성')||sys.includes('구역 생성')||user.includes('JSON만 출력:'))return JSON.stringify({name:'새 시설',theme:'반복 현상',rooms:smallRooms()});return JSON.stringify({narration:'남은 기록을 조용히 비교한다.',choices:[],effects:{}})};
 aiTurn=liveAiTurn;maybeSummarize=async()=>{};checkState=checkState;
 seed('campus');G.campaign={version:1,links:{},introSolved:false};G._deductionVersion=1;G._privateMysteryVersion=1;
 `)}
async function root(f){setupAI(f);assert.equal(await f.run('genCampaignWorld()'),true)}
async function intro(f){await root(f);await f.run('startIntroMystery()')}
async function collect(f){for(const room of ['r1','r2','r3']){f.run('G.site.cur='+JSON.stringify(room));await f.run("aiTurn('이 공간을 조사한다')")}}
async function proof(f,guess='h2',ids=['e2','e3']){f.run('submitMysteryProof('+JSON.stringify(guess)+','+JSON.stringify(ids)+')');await new Promise(r=>setImmediate(r))}
let count=0;async function test(name,fn){const f=fixture();await fn(f);count++;console.log('PASS',name)}
(async()=>{
await test('New campaign is designed and reviewed before locking; three private links are absent from public context',async f=>{await root(f);assert.equal(f.run('campaignPlan().chapters.length'),3);assert.equal(f.run('api.length'),2);const prompt=f.run("buildPrompt('교실을 바라본다','')");for(const sentinel of ['ROOT_SECRET_853','PRIVATE_FRAGMENT_','LINK_lacuna','PRIVATE_LORE_'])assert.ok(!prompt.includes(sentinel),sentinel);assert.ok(!f.run('sysBase()').includes('일곱'));assert.match(f.run('sysBase()'),/주요 지역 세 곳/)});
await test('World design rejects broken plans and failed independent reviews without saving answers',async f=>{setupAI(f);f.run('let callsN=0;callAI=async()=>{callsN++;return JSON.stringify({truth:"broken"})}');assert.equal(await f.run('genCampaignWorld()'),false);assert.equal(f.run('callsN'),2);assert.equal(f.run('G.campaign.world.status'),'pending');assert.equal(f.run('G.secret||null'),null);await f.run('startIntroMystery()');assert.equal(f.run('G.site'),null);});
await test('Review failure retries world generation; fixed world and local mysteries survive reload without new AI calls',async f=>{setupAI(f);f.run('const goodAI=callAI;let reviews=0;callAI=async(sys,user)=>sys.includes("본편의 독립 검토자")&&++reviews===1?JSON.stringify({valid:false,issues:["PRIVATE_REVIEW_ROOT"]}):goodAI(sys,user)');assert.equal(await f.run('genCampaignWorld()'),true);assert.equal(f.run('reviews'),2);await f.run('startIntroMystery()');const sealed=f.run('G.site.mystery.sealed'),world=f.run('G.campaign.world.sealed');f.run('G=JSON.parse(JSON.stringify(G));migrate();const apiBefore=api.length');await f.run('genCampaignWorld()');await f.run('ensureMystery()');assert.equal(f.run('G.campaign.world.sealed'),world);assert.equal(f.run('G.site.mystery.sealed'),sealed);assert.equal(f.run('apiBefore'),f.run('api.length'));assert.equal(f.run('G.fragments'),0)});
await test('World generation cannot overwrite a replacement game',async f=>{setupAI(f);f.run('let finish;callAI=()=>new Promise(resolve=>finish=resolve);const rootCandidate=worldDraft()');const job=f.run('genCampaignWorld()');f.run('seed("campus");finish(JSON.stringify(rootCandidate))');await job;assert.equal(f.run('G.campaign||null'),null);assert.equal(f.run('G.secret||null'),null)});
await test('Tampered fixed world is not regenerated or used to begin a new case',async f=>{await root(f);f.run('G.campaign.world.sealed+=" ";const apiBefore=api.length');assert.equal(await f.run('genCampaignWorld()'),false);assert.equal(f.run('apiBefore'),f.run('api.length'));await f.run('startIntroMystery()');assert.equal(f.run('G.site'),null)});
await test('Intro has exactly three reachable rooms and facts, no resource drain or darkness block, and survives leaving',async f=>{await intro(f);assert.equal(f.run('G.site.rooms.length'),3);assert.equal(f.run('mysteryPlan().evidence.length'),3);f.run('G.torch=0;const resourcesBefore=JSON.stringify({hp:G.hp,calm:G.calm,torch:G.torch,battery:G.battery});const introId=siteIdentity(G.site)');await collect(f);assert.equal(f.run('G.evidence.length'),3);assert.equal(f.run('resourcesBefore'),f.run('JSON.stringify({hp:G.hp,calm:G.calm,torch:G.torch,battery:G.battery})'));f.run('leaveIntroMystery()');assert.equal(f.run('G.loc'),'campus');assert.equal(f.run('G.district'),'music');await f.run('startIntroMystery()');assert.equal(f.run('siteIdentity(G.site)'),f.run('introId'));assert.equal(f.run('G.site.mystery.state.found.length'),3)});
await test('Hypotheses are hidden until evidence is complete and never include answer metadata in journal or public prompt',async f=>{await intro(f);assert.ok(!f.run('mysteryDeductionHTML()').includes('기록된 음원'));await collect(f);const ui=f.run('mysteryDeductionHTML()');assert.match(ui,/기록된 음원이/);assert.ok(!ui.includes('answer_id'));assert.ok(!ui.includes('CASE_SECRET_'));const prompt=f.run("buildPrompt('단서를 비교한다','')");assert.ok(!prompt.includes('CASE_SECRET_'));assert.ok(!prompt.includes('ROOT_SECRET_'));f.run('verifyMystery()');assert.match(f.run('modalHTML'),/mysterySupport/);assert.equal(f.run('G.site.mystery.state.solved'),false)});
await test('Wrong candidate and correct candidate with insufficient explanatory evidence remain retryable without revealing truth',async f=>{await intro(f);await collect(f);const sealed=f.run('G.site.mystery.sealed');await proof(f,'h1');assert.equal(f.run('G.site.mystery.state.solved'),false);await proof(f,'h2',['e1','e2']);assert.equal(f.run('G.site.mystery.state.solved'),false);assert.equal(f.run('G.site.mystery.state.attempts.length'),2);assert.equal(f.run('G.site.mystery.sealed'),sealed);assert.ok(!JSON.stringify(f.obj('events')).includes('CASE_SECRET_'));assert.ok(!JSON.stringify(f.obj('events')).includes('예약된 기록'));await proof(f);assert.equal(f.run('G.site.mystery.state.solved'),true);assert.equal(f.run('G.campaign.introSolved'),true);assert.equal(f.run('G.actDone'),true);assert.equal(f.run('G.fragments'),0)});
await test('Unknown, unrevealed, too few and duplicate proof IDs cannot consume time or solve',async f=>{await intro(f);await collect(f);const before=f.run('JSON.stringify({day:G.day,time:G.time,steps:G.steps})');for(const [g,ids] of [['h9',['e2','e3']],['h2',['e2']],['h2',['e2','e2']],['h2',['e2','future']]])await proof(f,g,ids);assert.equal(f.run('JSON.stringify({day:G.day,time:G.time,steps:G.steps})'),before);assert.equal(f.run('G.site.mystery.state.solved'),false)});
await test('Old automatic verification flag cannot bypass a new deduction; forged proof cannot solve before collecting evidence',async f=>{await intro(f);await collect(f);f.run("pend('',{mysteryVerify:siteIdentity(G.site)})");await f.run("aiTurn('확보한 근거로 원인을 검증한다')");assert.equal(f.run('G.site.mystery.state.solved'),false);f.run('G.site.mystery.state.found=[]');await proof(f);assert.equal(f.run('G.site.mystery.state.solved'),false)});
await test('New case validation rejects missing deduction, duplicate candidates and wrong main connection',async f=>{await intro(f);f.run('let p=caseDraft()');assert.equal(f.run('validateMystery(p,G.site).length'),0);f.run('delete p.deduction');assert.ok(f.run('validateMystery(p,G.site).length'));f.run('p=caseDraft();p.deduction.hypotheses[1].id="h1"');assert.ok(f.run('validateMystery(p,G.site).length'));f.run('p=caseDraft();G.site.big=true;G.site.key="lacuna";p.main_link="invented_connection"');assert.ok(f.run('validateMystery(p,G.site).length'))});
await test('Fragments and direct main calls cannot skip intro or a main case',async f=>{await root(f);f.run('G.fragments=8;checkState()');assert.equal(f.run('G.actDone||false'),false);await f.run('startBig("lacuna",true)');assert.equal(f.run('G.act'),1);f.run('G.site={big:true,key:"lacuna",rooms:[]};decodeRoster("진행 우회","")');assert.equal(f.run('G.act'),1);assert.equal(f.run('G.wards||null'),null);f.run('G.site={big:true,key:"c0",rooms:[]};wardFound("진행 우회","")');assert.equal(f.run('G.act'),1)});
await test('Full compact route solves intro and three main cases, publishes only earned links and reaches fixed ending',async f=>{
 await intro(f);await collect(f);await proof(f);f.run('leaveIntroMystery();G.act=2;G.torch=5;G.loc="site"');
 for(const key of ['lacuna','c0','c1']){
  f.run('G.loc="site"');await f.run('genBigZone(bigSpec('+JSON.stringify(key)+'))');assert.equal(f.run('G.site.rooms.length'),4);assert.equal(f.run('G.site.mystery.status'),'ready');assert.equal(f.run('G.campaign.links['+JSON.stringify(key)+']||null'),null);await collect(f);await proof(f);assert.equal(f.run('G.site.mystery.state.solved'),true);assert.equal(f.run('G.campaign.links['+JSON.stringify(key)+'].text'),'LINK_'+key+' 기록에 같은 식별자가 남아 있다.');f.run('G.site.cur=G.site.rooms.find(r=>r.heart).id');await f.run('openHeart()');await new Promise(r=>setImmediate(r));
  if(key==='lacuna'){assert.equal(f.run('G.act'),3);assert.equal(f.run('G.wards.length'),2);assert.equal(f.run('mainWardCount()'),2);assert.equal(f.run('campaignPublic().links.length'),1);assert.ok(!f.run('campaignPanel()').includes('LINK_c0'));assert.ok(!f.run("buildPrompt('검증 기록을 정리한다','')").includes('PRIVATE_LORE_c0'))}
 }
 assert.equal(f.run('G.act'),4);assert.equal(f.run('campaignPublic().links.length'),3);f.run('openEnding()');assert.match(f.run('modalHTML'),/ROOT_SECRET_853/);assert.match(f.run('modalHTML'),/LINK_lacuna/);assert.equal(f.run('G.wards.filter(c=>c.found).length'),2);
});
await test('Legacy seven-region saves retain their scale and old fixed answer, and new local cases can use deduction',f=>{f.run('seed();G.act=3;G.wards=WARD_ORDER.map((terrain,i)=>({id:"c"+i,terrain,found:i===0}));G._deductionVersion=1;const before=JSON.stringify(G.wards);migrate()');assert.equal(f.run('compactCampaign()'),false);assert.equal(f.run('mainWardCount()'),6);assert.equal(f.run('mainWardOrder().length'),6);assert.equal(f.run('JSON.stringify(G.wards)'),f.run('before'))});
await test('Intro clock passes class and roll-call boundaries without absence or demerits and offers no shelter detour',async f=>{await intro(f);f.run('G.time="낮";G.dayStep=CLASS_SLOTS[0];const beforeNotes=JSON.stringify({hp:G.hp,calm:G.calm,torch:G.torch,battery:G.battery,demerit:G.demerit});for(let i=0;i<35;i++)tick(false)');assert.equal(f.run('G.cls?.absent||0'),0);assert.equal(f.run('G.attendance?.totalAbsent||0'),0);assert.equal(f.run('beforeNotes'),f.run('JSON.stringify({hp:G.hp,calm:G.calm,torch:G.torch,battery:G.battery,demerit:G.demerit})'));assert.equal(f.run('gameActions().some(a=>a.id==="shelter:setup")'),false);f.run('shelterHere()');assert.equal(f.run('G.loc'),'site')});
await test('Current goal, fixed controls and guide render for compact game and stale deduction dialogs cannot submit',async f=>{await intro(f);await collect(f);f.run('const fixed=fixedHTML();const side=leftHTML();openGuide()');assert.match(f.run('fixed'),/교내로 돌아가기/);assert.match(f.run('fixed'),/원인 후보/);assert.match(f.run('side'),/선택 수집/);assert.match(f.run('modalHTML'),/총 3곳/);const before=f.run('JSON.stringify(G.site.mystery.state)');f.run('submitMysteryDeduction("old-zone-id")');assert.equal(f.run('JSON.stringify(G.site.mystery.state)'),before)});
console.log(`${count} campaign-overhaul scenario groups passed.`);
})().catch(e=>{console.error(e);process.exitCode=1});
