// Run: node tests/hanbit-resources.test.cjs
const crypto=require('node:crypto');
// Uses the actual game script. DOM/storage and network AI calls are stubbed.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../hanbit.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
function fixture(){
  const el={style:{},dataset:{},value:'',insertAdjacentHTML(){},remove(){},classList:{add(){},remove(){},contains(){return false},toggle(){}},addEventListener(){},querySelectorAll(){return []},setAttribute(){},getAttribute(){return null}};
  const ctx=vm.createContext({console,crypto:crypto.webcrypto,TextEncoder,URLSearchParams,AbortSignal,atob,btoa,setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{getElementById(){return el},querySelector(){return el},querySelectorAll(){return []},addEventListener(){},documentElement:el},window:{addEventListener(){},matchMedia(){return {matches:false,addEventListener(){}}}},navigator:{},URL,Blob,Math:Object.create(Math)});
  vm.runInContext(script.slice(0,script.indexOf('/* 시작: 화면 설정 적용')),ctx);
  const run=s=>vm.runInContext(s,ctx),obj=s=>JSON.parse(JSON.stringify(run(s)));
  run(`const liveSave=save;const calls=[],notices=[]; let chipHTML='',modalHTML='';
    addLog=()=>{};toast=s=>notices.push(s);render=()=>{};renderSides=()=>{};save=()=>{};sfx=()=>{};
    maybeIncoming=()=>{};closeModal=()=>{};apptRefresh=()=>{};renderChat=()=>{};askConfirm=async()=>true;const liveAiTurn=aiTurn;aiTurn=async(...args)=>calls.push(args);
    chip=s=>{chipHTML=s};hideChip=()=>{};modal=(title,s)=>{modalHTML=s};
    function seed(loc='site'){
      G={v:1,_phoneLightVersion:1,_fearBalanceVersion:1,_relVersion:2,_clockVersion:2,_affLv:2,char:{name:'테스트',age:17,stats:{str:1,wis:1,cha:1,sur:1},traits:[]},day:1,time:'방과 후',dayStep:0,loc,steps:0,hp:12,maxhp:12,calm:10,battery:6,torch:0,cash:100,items:[],mat:{metal:0,ply:0,wire:0,keepsake:0},act:1,fragments:0,sitesDone:0,district:'music',comp:{met:false,joined:false,aff:10},rel:{},chronicle:[],site:loc==='site'?{name:'피아노 괴담 구역',pos:{x:225,y:180},depth:1,cur:'r1',rooms:[{id:'r1',name:'입구',lv:0,danger:0,visited:true,exits:['r2','r3']},{id:'r2',name:'피아노실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r3',name:'방송실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r4',name:'창고',lv:2,danger:0,visited:true,exits:['r3']}]}:null};
      busy=false;PENDING={note:'',flags:{}};migrate();syncSchedule();Math.random=()=>0.99;calls.length=notices.length=0;chipHTML=modalHTML='';
    }
    seed('campus');G.comp.met=true;getRel('유민');getRel('서연');G.comp.spot='market';G.comp.spotKey=yKey();
  `);
  return {run,obj,input:el,ctx};
}


let count=0;
async function test(name,fn){await fn(fixture());count++;console.log('PASS',name)}
(async()=>{
await test('99% accepts outlet charging and ends at a genuine 100%',({run})=>{run("seed('campus');textDrain(1)");assert.equal(run('batteryPct()'),99);run('dormCharge()');assert.equal(run('batteryPct()'),100);assert.equal(run('G.textUse'),0);assert.equal(run('dormSt().charge'),1)});
await test('Outlet partial charge adds exactly 50 percentage points including residue',({run})=>{run("seed('campus');G.battery=1;textDrain(10);const before=batteryEnergy();dormCharge()");assert.ok(Math.abs(run('batteryEnergy()-before')-3)<1e-8);assert.equal(run('batteryPct()'),57)});
await test('Sleep charges residual debt at integer capacity; repeated full charge is stable',({run})=>{run("seed('campus');textDrain(10);sleepCharge('기숙사');sleepCharge('기숙사')");assert.equal(run('batteryPct()'),100);assert.equal(run('G.textUse'),0)});
await test('Paid fill reaches 100% and charges the displayed rounded pack count',({run})=>{run("seed('campus');openShop=()=>{};G.battery=3;G.textUse=10;fillSupply('battery')");assert.equal(run('batteryPct()'),100);assert.equal(run('G.cash'),88)});
await test('Single pack, item and peddler charging also honor fractional debt',({run})=>{run("seed('campus');openShop=()=>{};textDrain(1);buy('battery',3)");assert.equal(run('batteryPct()'),100);run("seed('campus');textDrain(1);G.items=['보조배터리'];useItem(0)");assert.equal(run('batteryPct()'),100);assert.equal(run('G.items.length'),0);run("seed('road');G.peddler={here:true,loc:'road',day:1,stock:{battery:3}};openPeddler=()=>{};textDrain(1);peddlerBuy('battery',1)");assert.equal(run('batteryPct()'),100);assert.equal(run('G.peddler.stock.battery'),2)});
await test('100 one-percent drains exactly exhaust the old cell representation',({run})=>{run("seed('campus');for(let i=0;i<99;i++)textDrain(1)");assert.equal(run('batteryPct()'),1);run('textDrain(1)');assert.equal(run('batteryPct()'),0);assert.equal(run('G.battery'),0);assert.equal(run('phoneBlock().includes("배터리")'),true)});
await test('Near-empty display stays at 1% until power is actually exhausted',({run})=>{run("seed('campus');setBatteryEnergy(0.001)");assert.equal(run('batteryPct()'),1);run('textDrain(1)');assert.equal(run('batteryPct()'),0)});
await test('Phone discharge alone does not injure, but switches off automatic light',({run})=>{run("seed();G.battery=0;G.steps=4;tick()");assert.equal(run('G.hp'),12);assert.equal(run('inDark()'),true)});
await test('Travel without phone power hurts only for insufficient composure',({run})=>{run("seed('road');G.battery=0;travelPay({days:0,calm:0,battery:10,feed:0},false)");assert.equal(run('G.hp'),12);run('G.calm=0;travelPay({days:0,calm:2,battery:10,feed:0},false)');assert.equal(run('G.hp'),10)});
await test('Investigation and movement consume phone-light power per action',({run})=>{run('seed();for(let i=0;i<20;i++)tick(true)');assert.equal(run('batteryPct()'),78);run("seed();for(let i=0;i<5;i++)moveTo(i%2?'r1':'r2')");assert.equal(run('batteryPct()'),95)});
await test('Tunnel phone-light drain is two percent per action',({run})=>{run("seed();G.site.terrain='tunnel';for(let i=0;i<3;i++)tick(true)");assert.equal(run('batteryPct()'),94);run('tick(true)');assert.equal(run('batteryPct()'),92)});
await test('Lit rooms do not consume light or apply darkness penalties',({run})=>{run("seed();G.site.rooms[0].light='lit';G.battery=0;G.textUse=0;for(let i=0;i<10;i++)tick(true)");assert.equal(run('inDark()'),false);assert.equal(run('G.site.lightActions||0'),0)});
await test('Outdoor daylight ends at night; indoor darkness and night sight stay compatible',({run})=>{run("seed();G.battery=0;G.textUse=0;G.time='낮';G.site.rooms[0].light='outdoor'");assert.equal(run('inDark()'),false);run("G.time='야간'");assert.equal(run('inDark()'),true);run("G.char.traits=['밤눈']");assert.equal(run('inDark()'),false)});
await test('Lighting metadata survives room normalization, unknown modes default to dark',({run})=>{run("seed();G.site.rooms=normRooms([{id:'r1',name:'정원',light:'outdoor',exits:['r2']},{id:'r2',name:'홀',light:'lit',exits:['r1']}],2)");assert.equal(run('G.site.rooms[0].light'),'outdoor');assert.equal(run('G.site.rooms[1].light'),'lit')});
await test('Ordinary dorm and paid lodging recover three fear without bypassing their costs',async({run})=>{run("seed('campus');G.calm=0;campusRest()");assert.equal(run('fearNow()'),7);run("seed('hood');G.hood='south';G.calm=0");await run('hoodRest()');assert.equal(run('fearNow()'),7);assert.equal(run('G.cash'),85)});
await test('Physical drink storage leaves fear unchanged and drinking consumes exactly one',({run})=>{run("seed('home');G.home.built.locker=true;G.calm=2;G.calmDrinks=2;lockerMove('calm','in',1);lockerMove('calm','out',1)");assert.equal(run('G.calm'),2);assert.equal(run('G.calmDrinks'),2);run('useCalmDrink()');assert.equal(run('G.calm'),3);assert.equal(run('G.calmDrinks'),1)});
await test('Composure alone cannot be deposited; old stored drinks survive repeated migration',({run})=>{run("seed('home');G.home.built.locker=true;lockerMove('calm','in',99)");assert.equal(run('G.calm'),10);assert.equal(run('lockerStock().calm'),0);run('G.home.stock.calm=3;migrate();migrate();lockerMove("calm","out",2)');assert.equal(run('G.calm'),10);assert.equal(run('G.calmDrinks'),2);assert.equal(run('G.home.stock.calm'),1)});
await test('Buying a bottled drink costs cash but changes fear only on use',({run})=>{run("seed('campus');openShop=()=>{};G.calm=1;buyCalmDrink()");assert.equal(run('G.calm'),1);assert.equal(run('G.cash'),98);assert.equal(run('G.calmDrinks'),1);run('useCalmDrink()');assert.equal(run('G.calm'),2)});
await test('Battery storage preserves residue and cannot deposit a nonexistent full cell',({run})=>{run("seed('home');G.home.built.locker=true;setBatteryEnergy(1.5);lockerMove('battery','in',99)");assert.ok(Math.abs(run('batteryEnergy()')-.5)<1e-8);assert.equal(run('lockerStock().battery'),1);run("lockerMove('battery','out',1)");assert.ok(Math.abs(run('batteryEnergy()')-1.5)<1e-8)});
await test('Daytime home charging is useful, consumes time and enforces a daily quota',({run})=>{run("seed('home');G.home.built.charger=true;G.battery=0;G.time='낮';homeCharge();homeCharge()");assert.equal(run('batteryPct()'),100);assert.equal(run('G.dayStep'),2);run('textDrain(20);homeCharge()');assert.equal(run('batteryPct()'),80);assert.equal(run('G.home.chargeN'),2)});
await test('Nonexistent sale items cannot bypass cash limits or permit healing',({run})=>{run("seed('campus');G.hp=2;applyEffects({cash:40,hp:4,items_remove:['없는 물건']},{action:'물건을 판다',flags:{}});applyEffects({cash:40,items_remove:['없는 물건']},{flags:{}})");assert.equal(run('G.cash'),100);assert.equal(run('G.hp'),2)});
await test('Actual sale is priced by code and cannot be repeated after item removal',({run})=>{run("seed('campus');G.items=['고철 장식'];const price=itemSellPrice('고철 장식');applyEffects({cash:40,items_remove:['고철 장식']},{action:'고철 장식을 판매한다',flags:{}})");assert.equal(run('G.cash'),run('100+price'));assert.equal(run('G.items.length'),0);run("applyEffects({cash:40,items_remove:['고철 장식']},{action:'고철 장식을 판매한다',flags:{}})");assert.equal(run('G.cash'),run('100+price'))});
await test('Zone cash quota counts actual bounded payments: 40 + 40 + 10',({run})=>{run('seed();applyEffects({cash:100},{flags:{}})');assert.equal(run('G.cash'),140);assert.equal(run('G.site.cashGot'),40);run('applyEffects({cash:100},{flags:{}});applyEffects({cash:100},{flags:{}})');assert.equal(run('G.cash'),190);assert.equal(run('G.site.cashGot'),90)});
await test('A real wage AI turn cannot pay twice or consume story reward quota',async({run})=>{run("seed('campus');G.district='snack';let pendingStory;aiTurn=(...args)=>pendingStory=liveAiTurn(...args);queueLex=()=>{};maybeSummarize=async()=>{};callAI=async()=>JSON.stringify({narration:'일을 마쳤다.',choices:[],effects:{캐시:8,배터리:2,items_add:['보조배터리']}});textDrain(10);const charge=batteryEnergy();doJob('snack')");await run('pendingStory');assert.equal(run('G.cash'),108);assert.equal(run('G._cashDay?.got||0'),0);assert.equal(run('batteryEnergy()'),run('charge'));assert.equal(run('G.items.length'),0)});
await test('Outlet AI turns cannot repeat resource changes through consumable items',async({run})=>{run("seed('campus');let pendingStory;aiTurn=(...args)=>pendingStory=liveAiTurn(...args);queueLex=()=>{};maybeSummarize=async()=>{};callAI=async()=>JSON.stringify({narration:'잠깐 충전했다.',choices:[],effects:{배터리:2,공포:-2,items_add:['보조배터리']}});G.battery=1;G.calm=1;dormCharge()");await run('pendingStory');assert.equal(run('G.battery'),4);assert.equal(run('G.calm'),1)});
await test('Uncorroborated manual medals cannot mint the completion bonus',({run})=>{run("seed('campus');for(let i=0;i<6;i++)fragManualDo()");assert.equal(run('G.fragments'),0);assert.equal(run('G.cash'),100)});
await test('Six actual medal items convert once and pay the existing 300 bonus once',({run})=>{run("seed('campus');G.items=Array(6).fill('기념 메달 조각');for(let i=0;i<6;i++)fragManualDo();checkState();grantMedalReward()");assert.equal(run('G.fragments'),6);assert.equal(run('G.cash'),400);assert.equal(run('G.items.length'),0);assert.equal(run('fragManualDo()'),false)});
await test('Legacy correction uses the current witnessed fragment room exactly once',({run})=>{run("seed();G.site.rooms[0].fragment=true;lastScene=()=> '기념 메달 조각을 발견하고 손에 넣었다.';fragManualDo();fragManualDo()");assert.equal(run('G.fragments'),1);assert.equal(run('G.site.rooms[0].fragTaken'),true)});
await test('Pending manual correction cannot alter a replaced save',async({run})=>{run("seed('campus');G.items=['기념 메달 조각'];let confirm;askConfirm=()=>new Promise(r=>confirm=r);const pending=fragManual();seed('campus');G.items=['기념 메달 조각'];confirm(true)");await run('pending');assert.equal(run('G.fragments'),0);assert.equal(run('G.items.length'),1)});
await test('Legacy battery residue and existing records survive idempotent migration',({run})=>{run("seed('home');G.textUse=10;G.home.stock={calm:4,battery:2,torch:1};G.canon=[{text:'확정 기록'}];G.medalRewardClaimed=true;const before=JSON.stringify({battery:G.battery,textUse:G.textUse,stock:G.home.stock,canon:G.canon});migrate();migrate()");assert.equal(run('before'),run('JSON.stringify({battery:G.battery,textUse:G.textUse,stock:G.home.stock,canon:G.canon})'));assert.equal(run('G.medalRewardClaimed'),true)});

await test('No-money turns do not silently consume cash quota',({run})=>{run('seed();applyEffects({cash:40},{flags:{noMoney:true}})');assert.equal(run('G.cash'),100);assert.equal(run('G.site.cashGot||0'),0);run("seed('campus');applyEffects({cash:40},{flags:{noMoney:true}})");assert.equal(run('G._cashDay?.got||0'),0)});
await test('Weekend visit pays once even when AI repeats cash and snack effects',async({run})=>{run("seed('campus');G.day=6;G.time='낮';G.dayStep=4;syncSchedule();let pendingStory;aiTurn=(...args)=>pendingStory=liveAiTurn(...args);queueLex=()=>{};maybeSummarize=async()=>{};callAI=async()=>JSON.stringify({narration:'안부를 나눴다.',choices:[],effects:{캐시:20,items_add:['초코바']}});visitHour()");await run('pendingStory');assert.equal(run('G.cash'),120);assert.equal(run('G.items.length'),1)});

await test('Capacity expansion preserves existing power and later percentage drain uses the new capacity',({run})=>{run("seed('campus');textDrain(10);const power=batteryEnergy();G.cap.f=1");assert.ok(Math.abs(run('batteryEnergy()-power'))<1e-8);run('textDrain(1)');assert.ok(Math.abs(run('batteryEnergy()')-5.32)<1e-8);assert.equal(run('G._batteryResidueCap'),8)});
console.log(`${count} resource-integrity scenario groups passed.`);
})().catch(err=>{console.error(err);process.exitCode=1});
