// Run: node tests/hanbit-cases-actions.test.cjs
// Uses the actual game script. DOM/storage and network AI calls are stubbed.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../hanbit.html'),'utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
function fixture(){
  const el={style:{},dataset:{},value:'',insertAdjacentHTML(){},remove(){},classList:{add(){},remove(){},contains(){return false},toggle(){}},addEventListener(){},querySelectorAll(){return []},setAttribute(){},getAttribute(){return null}};
  const ctx=vm.createContext({console,setTimeout(){return 0},clearTimeout(){},setInterval(){return 0},clearInterval(){},localStorage:{getItem(){return null},setItem(){}},document:{getElementById(){return el},querySelector(){return el},querySelectorAll(){return []},addEventListener(){},documentElement:el},window:{addEventListener(){},matchMedia(){return {matches:false,addEventListener(){}}}},navigator:{},URL,Blob,Math:Object.create(Math)});
  vm.runInContext(script.slice(0,script.indexOf('/* 시작: 화면 설정 적용')),ctx);
  const run=s=>vm.runInContext(s,ctx),obj=s=>JSON.parse(JSON.stringify(run(s)));
  run(`const calls=[],notices=[]; let chipHTML='',modalHTML='';
    addLog=()=>{};toast=s=>notices.push(s);render=()=>{};renderSides=()=>{};save=()=>{};sfx=()=>{};
    maybeIncoming=()=>{};closeModal=()=>{};apptRefresh=()=>{};renderChat=()=>{};askConfirm=async()=>true;const liveAiTurn=aiTurn;aiTurn=async(...args)=>calls.push(args);
    chip=s=>{chipHTML=s};hideChip=()=>{};modal=(title,s)=>{modalHTML=s};
    function seed(loc='site'){
      G={v:1,_phoneLightVersion:1,_fearBalanceVersion:1,_relVersion:2,_clockVersion:2,_affLv:2,char:{name:'테스트',age:17,stats:{str:1,wis:1,cha:1,sur:1},traits:[]},day:1,time:'방과 후',dayStep:0,loc,steps:0,hp:12,maxhp:12,calm:10,battery:6,torch:0,cash:100,items:[],mat:{metal:0,ply:0,wire:0,keepsake:0},act:1,fragments:0,sitesDone:0,district:'music',comp:{met:false,joined:false,aff:10},rel:{},chronicle:[],site:loc==='site'?{name:'피아노 괴담 구역',pos:{x:225,y:180},depth:1,cur:'r1',rooms:[{id:'r1',name:'입구',lv:0,danger:0,visited:true,exits:['r2','r3']},{id:'r2',name:'피아노실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r3',name:'방송실',lv:1,danger:0,visited:true,exits:['r1']},{id:'r4',name:'창고',lv:2,danger:0,visited:true,exits:['r3']}]}:null};
      busy=false;PENDING={note:'',flags:{}};migrate();syncSchedule();Math.random=()=>0.99;calls.length=notices.length=0;chipHTML=modalHTML='';
    }
    seed('campus');G.comp.met=true;getRel('유민');getRel('서연');G.comp.spot='market';G.comp.spotKey=yKey();
  `);
  return {run,obj,input:el};
}
const candidate={question:'빈 방에서 소리가 반복되는 이유는?',opening:'낡은 입구의 공기는 차갑고 조용하다.',truth:'PRIVATE_TRUTH_735 비공개 원인은 예약 재생 장치다.',conclusion:'PRIVATE_CONCLUSION_912 예약 장치가 다른 방으로 녹음을 전송했다.',room_views:['r1','r2','r3','r4'].map(room=>({room,text:'빛이 닿은 바닥과 오래된 문틀이 보인다.'})),evidence:[{id:'e1',room:'r1',text:'종이에 03:15라는 시간이 세 번 적혀 있다.',meaning:'반복되는 시간이 조사 기준이 된다.'},{id:'e2',room:'r2',text:'음원이 매번 정확히 같은 구간에서 끊긴다.',meaning:'연주보다 동일한 기록의 반복을 뒷받침한다.'},{id:'e3',room:'r3',text:'두 방 사이를 연결한 선에 같은 번호가 붙어 있다.',meaning:'소리가 이동하는 경로를 추적할 근거다.'}],verification:{room:'r3',action:'번호가 같은 선의 전송을 끊고 소리가 멎는지 확인한다',requires:['e1','e2','e3'],result:'PRIVATE_RESULT_624 전송을 끊자 반복되던 소리가 함께 멎었다.'}};
async function prepared(f){f.run("seed('site');G.secret={truth:'WORLD_SECRET_479',detail:'아직 알려지지 않은 세계의 진상'};G.site.rooms.forEach(r=>r.desc='ROOM_SECRET_381');const events=[],api=[];addLog=(type,text)=>events.push({type,text});let proposal="+JSON.stringify(candidate)+";callAI=async(sys,user)=>{api.push({sys,user});return JSON.stringify(sys.includes('독립 검토자')?{valid:true,issues:[]}:proposal)};");await f.run('ensureMystery()');f.run("aiTurn=liveAiTurn;callAI=async(sys,user)=>{api.push({sys,user});return JSON.stringify({narration:'공간에 남은 흔적을 살펴본다.',choices:[],effects:{사건진행:[{case_id:G.site.caseId,evidence:[{text:'AI가 지어낸 새로운 핵심 증거',kind:'fact',role:'narrows'}]}]}})};maybeSummarize=async()=>{};checkState=()=>{};");}
let count=0;async function test(name,fn){const f=fixture();await fn(f);count++;console.log('PASS',name)}
(async()=>{
await test('Hidden generation passes structural and independent semantic review before locking',async f=>{await prepared(f);assert.equal(f.run('G.site.mystery.status'),'ready');assert.equal(f.run('api.length'),2);assert.equal(f.run('G.evidence.length'),0);assert.equal(f.run('G.site.mystery.state.solved'),false);assert.equal(f.run('mysteryPlan().truth'),candidate.truth)});
await test('Narrator and journal do not receive the answer, unseen clues, private room memo or world secret',async f=>{await prepared(f);const prompt=f.run("buildPrompt('입구를 바라본다','')");for(const value of [candidate.truth,candidate.conclusion,candidate.verification.result,candidate.evidence[0].text,'ROOM_SECRET_381','WORLD_SECRET_479'])assert.ok(!prompt.includes(value),value);f.run('openZoneJournal()');assert.ok(!f.run('modalHTML').includes(candidate.truth));assert.ok(!f.run('modalHTML').includes(candidate.evidence[0].text));});
await test('Malformed plans are rejected before review; retry is bounded',async f=>{f.run('seed();let n=0;callAI=async()=>{n++;return JSON.stringify({question:"不完全"})}');await f.run('ensureMystery()');assert.equal(f.run('n'),2);assert.equal(f.run('G.site.mystery.status'),'pending');assert.equal(f.run('G.site.caseId||null'),null)});
await test('Bad references, inaccessible evidence, duplicates and insufficient verification are rejected',f=>{
 f.run('seed();let p='+JSON.stringify(candidate));assert.equal(f.run('validateMystery(p,G.site).length'),0);
 for(const mutation of ["p.evidence[0].room='unknown'","p.evidence[1].id='e1'","p.evidence[1].room='r1'","p.verification.requires=['e1']","p.room_views.pop()","p.verification.room='r4'"]){f.run('p='+JSON.stringify(candidate)+';'+mutation);assert.ok(f.run('validateMystery(p,G.site).length')>0,mutation)}
});
await test('Independent review rejection triggers regeneration and never prints private issues',async f=>{f.run('seed();let designs=0;let reviews=0;callAI=async(sys)=>{if(sys.includes("독립 검토자")){reviews++;return JSON.stringify({valid:reviews>1,issues:["PRIVATE_REVIEW_714 정답 유출"]})} designs++;return JSON.stringify('+JSON.stringify(candidate)+')};const events=[];addLog=(type,text)=>events.push({type,text})');await f.run('ensureMystery()');assert.equal(f.run('designs'),2);assert.equal(f.run('reviews'),2);assert.equal(f.run('G.site.mystery.status'),'ready');assert.ok(!JSON.stringify(f.obj('events')).includes('PRIVATE_REVIEW_714'));});
await test('Prepared facts stay fixed through save/load and repeat preparation consumes no AI calls',async f=>{await prepared(f);const sealed=f.run('G.site.mystery.sealed');f.run('G=JSON.parse(JSON.stringify(G));migrate();const before=api.length');await f.run('ensureMystery()');assert.equal(f.run('G.site.mystery.sealed'),sealed);assert.equal(f.run('api.length'),f.run('before'));});
await test('Tampered locked facts stop play instead of generating another answer',async f=>{await prepared(f);f.run('G.site.mystery.sealed+=" ";const before=api.length');await f.run('ensureMystery()');assert.equal(f.run('api.length'),f.run('before'));assert.equal(f.run('mysteryPlan()'),null)});
await test('Preparation cannot write to a replacement game while awaiting AI',async f=>{f.run('seed();let finish;callAI=()=>new Promise(r=>finish=r)');const job=f.run('ensureMystery()');f.run('seed();finish(JSON.stringify('+JSON.stringify(candidate)+'))');await job;assert.equal(f.run('G.site.mystery||null'),null)});
await test('Concurrent preparation shares one generation and review',async f=>{f.run('seed();let callsN=0;let finish;callAI=async(sys)=>{callsN++;if(sys.includes("독립 검토자"))return JSON.stringify({valid:true});return new Promise(r=>finish=r)}');const a=f.run('ensureMystery()'),b=f.run('ensureMystery()');f.run('finish(JSON.stringify('+JSON.stringify(candidate)+'))');await Promise.all([a,b]);assert.equal(f.run('callsN'),2);});
await test('Investigation publishes only the current prepared fact and its contribution',async f=>{await prepared(f);await f.run("aiTurn('周囲를 조사한다')");assert.equal(f.run('G.site.mystery.state.found.length'),1);assert.equal(f.run('G.evidence[0].text'),candidate.evidence[0].text);const last=f.obj('api').at(-1).user;assert.ok(last.includes(candidate.evidence[0].text));assert.ok(!last.includes(candidate.evidence[1].text));assert.ok(!last.includes(candidate.truth));assert.ok(f.obj('events').some(e=>e.text.includes('사건 진행:')));});
await test('Repeated investigation reports no extra finding without inventing evidence',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");await f.run("aiTurn('입구를 다시 조사한다')");assert.equal(f.run('G.evidence.length'),1);assert.ok(f.obj('events').some(e=>e.text.includes('추가 발견 없음')));});
await test('Darkness and story-only turns cannot reveal prepared evidence',async f=>{await prepared(f);f.run('G.battery=0;G.textUse=0');await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence.length'),0);assert.ok(f.obj('events').some(e=>e.text.includes('관찰 불가')));f.run("G.battery=6;G.textUse=0;pend('',{storyOnly:true})");await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence.length'),0)});
await test('Registered investigation reveals evidence even with new display wording',async f=>{await prepared(f);f.run("dispatchGameAction(roomActionId('investigate','r1'),'소리에 집중한다')");await new Promise(r=>setImmediate(r));assert.equal(f.run('G.evidence.length'),1)});
await test('Evidence collection does not solve the case; verified action does',async f=>{await prepared(f);for(const room of ['r1','r2','r3']){f.run('G.site.cur='+JSON.stringify(room));await f.run("aiTurn('이 공간을 조사한다')");}assert.equal(f.run('G.evidence.length'),3);assert.equal(f.run('G.threads.find(t=>t.id===G.site.caseId).status'),'open');assert.equal(f.run('G.site.mystery.state.solved'),false);assert.equal(f.run('canVerifyMystery()'),true);assert.ok(f.run('gameActions().some(a=>a.id===mysteryVerifyId())'));f.run('verifyMystery()');await new Promise(r=>setImmediate(r));assert.equal(f.run('G.site.mystery.state.solved'),true);assert.equal(f.run('G.threads.find(t=>t.id===G.site.caseId).status'),'closed');assert.equal(f.run('mysteryPublic().conclusion'),candidate.conclusion)});
await test('Manual conclusion, AI case updates and legacy lore finalize cannot bypass verification',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('resolveCase(G.site.caseId,'+JSON.stringify(candidate.conclusion)+',[G.evidence[0].id],true)'),false);f.run('applyCaseUpdates([{case_id:G.site.caseId,resolution:{conclusion:'+JSON.stringify(candidate.conclusion)+',support_ids:[G.evidence[0].id]}}]);G.site.lore={recorded:false,record:"LEAK_PRIVATE_LORE_647"};finalizeZone(G.site);');assert.equal(f.run('G.site.mystery.state.solved'),false);assert.ok(!JSON.stringify(f.obj('G.lexicon')).includes('LEAK_PRIVATE_LORE_647'));});
await test('Visiting every room keeps unsolved zones resumable',async f=>{await prepared(f);f.run('G.site.rooms.forEach(r=>r.visited=true);const sealed=G.site.mystery.sealed');assert.equal(f.run('siteProg().done'),false);f.run('archiveSite()');assert.equal(f.run('G.pausedZones.length'),1);assert.equal(f.run('G.pausedZones[0].mystery.sealed'),f.run('sealed'));});
await test('Generation failure blocks investigation without consuming another clock tick',async f=>{f.run("seed();callAI=async()=>{throw new Error('NO_KEY')};const before=JSON.stringify({day:G.day,time:G.time,steps:G.steps})");await f.run('ensureMystery()');f.run("story('입구를 조사한다')");assert.equal(f.run('before'),f.run('JSON.stringify({day:G.day,time:G.time,steps:G.steps})'));assert.equal(f.run('G.evidence.length'),0);});
await test('AI outage during play still publishes the prepared fact',async f=>{await prepared(f);f.run("callAI=async()=>{throw new Error('NO_KEY')}");await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.evidence[0].text'),candidate.evidence[0].text);assert.ok(f.obj('events').some(e=>e.type==='scene'&&e.text.includes(candidate.evidence[0].text)));});
await test('Management cannot park a fixed case or offer a misleading manual resolution',async f=>{await prepared(f);f.run('const t=G.threads.find(t=>t.id===G.site.caseId);closeThread(t.id)');assert.equal(f.run('t.status'),'open');assert.ok(!f.run('caseCard(t)').includes('결론 기록'));assert.match(f.run('caseCard(t)'),/원인 검증/)});
await test('Legacy observed records survive conversion into a fixed mystery',async f=>{f.run('seed();const t=caseRecord("기존에 조사한 질문",{scope:"local",placeId:knowledgePlace()});G.site.caseId=t.id;addCanon("이미 확인한 낡은 흔적이 남아 있다",true,true,{caseId:t.id});G.site.lore={what:"기존의 확정된 경위가 있다",fate:"폐쇄 후 버려졌다"};const original=JSON.stringify(G.evidence);callAI=async(sys)=>JSON.stringify(sys.includes("독립 검토자")?{valid:true}:'+JSON.stringify(candidate)+')');await f.run('ensureMystery()');assert.equal(f.run('JSON.stringify(G.evidence)'),f.run('original'));assert.equal(f.run('G.site.caseId'),f.run('t.id'));assert.equal(f.run('G.site.mystery.status'),'ready');});
await test('A generated ordinary zone prepares and reviews its hidden case before returning the public introduction',async f=>{
 f.run('seed();ensureAncient=async()=>{};G.ancient=[];let generation=0;callAI=async(sys)=>{if(sys.includes("독립 검토자"))return JSON.stringify({valid:true});if(sys.includes("비공개 미스터리 설계자"))return JSON.stringify('+JSON.stringify(candidate)+');generation++;return JSON.stringify({name:"음원이 반복되는 별관",theme:"OLD_PRIVATE_THEME",intro:"UNREVIEWED_INTRO",rooms:G.site.rooms})};');const intro=await f.run('genSite()');assert.equal(intro,candidate.opening);assert.equal(f.run('G.site.mystery.status'),'ready');assert.equal(f.run('generation'),1);assert.ok(!f.run("buildPrompt('조사한다','')").includes('OLD_PRIVATE_THEME'));
});
await test('Verification is unavailable before all evidence and outside the registered room',async f=>{await prepared(f);assert.equal(f.run('canVerifyMystery()'),false);for(const room of ['r1','r2','r3']){f.run('G.site.cur='+JSON.stringify(room));await f.run("aiTurn('이 공간을 조사한다')");}f.run("G.site.cur='r1'");assert.equal(f.run('canVerifyMystery()'),false);f.run('verifyMystery()');assert.equal(f.run('G.site.mystery.state.solved'),false)});
await test('Damaged progress state stops a locked case without regenerating it',async f=>{await prepared(f);f.run('delete G.site.mystery.state;const before=api.length');assert.equal(f.run('mysteryPlan()'),null);await f.run('ensureMystery()');assert.equal(f.run('api.length'),f.run('before'))});
await test('A main ward also prepares its case before exposing an introduction',async f=>{f.run('seed();G.wards=[{terrain:Object.keys(WARD_TYPES)[0],id:"testward",name:"고요한 구역",mood:"침묵",lore:"WARD_PRIVATE_SECRET"}];wardArrive=()=>{};callAI=async(sys)=>JSON.stringify(sys.includes("독립 검토자")?{valid:true}:sys.includes("비공개 미스터리 설계자")?'+JSON.stringify(candidate)+':{theme:"OLD_WARD_THEME",intro:"UNREVIEWED_WARD_INTRO",rooms:G.site.rooms});');const intro=await f.run('genBigZone({key:"testward",terrain:Object.keys(WARD_TYPES)[0],campus:G.wards[0],pos:[0,0]})');assert.equal(intro,candidate.opening);assert.equal(f.run('G.site.mystery.status'),'ready');assert.ok(!f.run("buildPrompt('조사한다','')").includes('WARD_PRIVATE_SECRET'))});
await test('Notebook distinguishes prepared core evidence from rumor, hypothesis and legacy facts without mutating records',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");f.run('const beforeNotes=JSON.stringify({canon:G.canon,evidence:G.evidence});const samples=[G.evidence[0],{kind:"rumor",text:"소문이 떠돈다"},{kind:"hypothesis",text:"아직은 추정이다"},{kind:"fact",source:"legacy",text:"오래된 확인 기록"},{kind:"testimony",source:"scene",text:"친구가 한 증언이다"}];const classified=samples.map(notebookCategory);const grouped=notebookGroupsHTML(samples)');assert.deepEqual(f.obj('classified'),['core','rumor','rumor','background','background']);assert.match(f.run('grouped'),/핵심 증거 · 1개/);assert.match(f.run('grouped'),/소문·가설 · 2개/);assert.match(f.run('grouped'),/배경 기록 · 2개/);assert.equal(f.run('beforeNotes'),f.run('JSON.stringify({canon:G.canon,evidence:G.evidence})'))});
await test('Notebook preserves old records beyond 50 entries and escapes their content',f=>{f.run('seed();G.canon=Array.from({length:55},(_,i)=>({text:"OLD_NOTE_"+i}));G.evidence=[{id:"standalone",text:"<script>alert(1)</script>",kind:"rumor"}];const beforeNotes=JSON.stringify(G.canon);openThreads()');assert.match(f.run('modalHTML'),/OLD_NOTE_0/);assert.match(f.run('modalHTML'),/OLD_NOTE_54/);assert.match(f.run('modalHTML'),/&lt;script&gt;/);assert.ok(!f.run('modalHTML').includes('<script>'));assert.equal(f.run('notebookRecords().length'),56);assert.equal(f.run('beforeNotes'),f.run('JSON.stringify(G.canon)'))});
await test('Core evidence cannot be deleted and old reference notes remain removable at their original index',async f=>{await prepared(f);await f.run("aiTurn('입구를 조사한다')");f.run('const coreId=G.evidence[0].id;delCanon(0)');assert.equal(f.run('G.evidence[0].deleted||false'),false);assert.equal(f.run('G.canon[0].id'),f.run('coreId'));f.run('G.canon.push({text:"OLD_REMOVABLE_RECORD"});const html=notebookGroupsHTML(notebookRecords(),true)');assert.ok(!f.run('html').includes('delCanon(0)'));assert.ok(f.run('html').includes('delCanon(1)'));f.run('delCanon(1)');assert.equal(f.run('G.canon.length'),1);assert.equal(f.run('G.canon[0].id'),f.run('coreId'))});
await test('System instructions use fixed answers and remove obsolete compact-campaign targets',f=>{
 f.run('seed();G.campaign={version:1};const instructions=sysBase()');
 assert.ok(!f.run('instructions').includes('진상(구역이 지워진 이유, 출석부의 정체, 교표의 비밀, 엔딩)은 정해져 있지 않다'));
 assert.ok(!f.run('instructions').includes('플레이 중 네가 일관되게 정하되'));
 assert.ok(!f.run('instructions').includes('6개 모으기'));
 assert.ok(!f.run('instructions').includes('애시우드 구역'));
 assert.ok(f.run('instructions').includes('정답·핵심 증거는 비공개 설계에 미리 정해져 있다'));
 f.run('delete G.campaign');assert.ok(f.run('sysBase()').includes('기념 메달 조각 6개 모으기'));
});
await test('A matching scene is reviewed before display without disclosing unseen evidence or answers',async f=>{
 await prepared(f);f.run(`const core=${JSON.stringify(candidate.evidence[0].text)};callAI=async(sys,user)=>{api.push({sys,user});return JSON.stringify(sys.includes('본문 일치 검토자')?{valid:true,issues:[]}:{narration:'바람이 문틈을 스친다. '+core,choices:[],effects:{}})}`);
 await f.run("aiTurn('입구를 조사한다')");assert.ok(f.obj('events').some(e=>e.type==='scene'&&e.text.includes('바람이')));
 const review=f.obj('api').at(-1);assert.match(review.sys,/본문 일치 검토자/);assert.ok(review.user.includes(candidate.evidence[0].text));
 for(const privateValue of [candidate.truth,candidate.conclusion,candidate.evidence[1].text,candidate.verification.result,'ROOM_SECRET_381','WORLD_SECRET_479'])assert.ok(!review.user.includes(privateValue),privateValue);
 assert.equal(f.run('G.site.mystery.state.found.length'),1);
});
await test('Omitted or numerically altered core text is replaced without needing reviewer approval',async f=>{
 await prepared(f);f.run("let reviewCalls=0;callAI=async(sys)=>{if(sys.includes('본문 일치 검토자'))reviewCalls++;return JSON.stringify({narration:'종이에 04:15라는 시간이 세 번 적혀 있다.',choices:['잘못된 시간을 입력한다'],chronicle:'잘못된 시간을 발견했다',effects:{체력:-9}})}");
 await f.run("aiTurn('입구를 조사한다')");const scene=f.obj('events').find(e=>e.type==='scene');assert.ok(scene.text.includes(candidate.evidence[0].text));assert.ok(!scene.text.includes('04:15'));assert.equal(f.run('reviewCalls'),0);assert.equal(f.run('G.hp'),12);assert.ok(!JSON.stringify(f.obj('G.recent')).includes('04:15'));assert.ok(!JSON.stringify(f.obj('G.chronicle')).includes('잘못된 시간'));
});
await test('Reviewer rejection discards invented discoveries, choices, chronology and effects',async f=>{
 await prepared(f);f.run("callAI=async(sys)=>JSON.stringify(sys.includes('본문 일치 검토자')?{valid:false,issues:['추가 발견은 공개 기록에 없음']}:{narration:'벽에서 HALLUCINATED_KEY를 발견한다.',choices:['HALLUCINATED_KEY로 문을 연다'],chronicle:'HALLUCINATED_KEY를 얻었다',effects:{items_add:[{name:'HALLUCINATED_KEY',key:true}]}})");
 await f.run("aiTurn('문 앞에서 잠시 기다린다')");assert.ok(!JSON.stringify(f.obj('events')).includes('HALLUCINATED_KEY'));assert.ok(!JSON.stringify(f.obj('G.recent')).includes('HALLUCINATED_KEY'));assert.ok(!JSON.stringify(f.obj('G.items')).includes('HALLUCINATED_KEY'));assert.equal(f.run('G.evidence.length'),0);assert.equal(f.run('busy'),false);
});
await test('Missing verdict, nonboolean verdict and connection failure use canonical fallback',async f=>{
 await prepared(f);f.run(`const core=${JSON.stringify(candidate.evidence[0].text)};const turn={g:G,loc:'site',action:'조사',flags:{privateMystery:true},mysteryOutcome:{d:G.site,type:'evidence',e:mysteryPlan().evidence[0]}};const submission={narration:core+' UNSAFE_EXTRA',choices:[],effects:{hp:-3}}`);
 for(const verdict of ['{}','{valid:"true",issues:[]}','{valid:true}','{valid:true,issues:["문제"]}','null']){
  f.run('callAI=async()=>JSON.stringify('+verdict+')');const result=await f.run('guardMysteryNarration(submission,turn,true)');assert.ok(result.narration.includes(candidate.evidence[0].text));assert.ok(!result.narration.includes('UNSAFE_EXTRA'));assert.deepEqual(Object.keys(result.effects),[]);
 }
 f.run('callAI=async()=>{throw Error("network failure")}');const result=await f.run('guardMysteryNarration(submission,turn,true)');assert.ok(!result.narration.includes('UNSAFE_EXTRA'));
});
await test('Exact private-answer leakage is blocked locally and never sent to the reviewer',async f=>{
 await prepared(f);f.run('let reviewCalls=0;callAI=async()=>{reviewCalls++;return JSON.stringify({valid:true,issues:[]})};const turn={g:G,loc:"site",action:"기다린다",flags:{}}');
 const result=await f.run('guardMysteryNarration({narration:'+JSON.stringify(candidate.truth)+',choices:[],effects:{}},turn,true)');assert.ok(!result.narration.includes(candidate.truth));assert.equal(f.run('reviewCalls'),0);
});
await test('Late narration review cannot mutate or unlock a replacement game',async f=>{
 await prepared(f);f.run(`let releaseReview;const core=${JSON.stringify(candidate.evidence[0].text)};callAI=async(sys)=>sys.includes('본문 일치 검토자')?new Promise(r=>releaseReview=r):JSON.stringify({narration:core,choices:[],effects:{}});const pending=aiTurn('입구를 조사한다')`);
 await new Promise(r=>setImmediate(r));assert.equal(f.run('typeof releaseReview'),'function');f.run('seed("campus");busy=true;const replacementTurn={g:G};curTurn=replacementTurn;G.choiceMeta={keep:{type:"story"}};releaseReview(JSON.stringify({valid:false,issues:["문제"]}))');await f.run('pending');assert.equal(f.run('busy'),true);assert.equal(f.run('curTurn===replacementTurn'),true);assert.equal(f.run('G.choiceMeta.keep.type'),'story');assert.equal(f.run('G.evidence.length'),0);
});
await test('Medal completion pays cash and bonus XP once, independently of main progress',f=>{
 f.run('seed("campus");G.campaign={version:1,links:{},introSolved:false};G.fragments=5;G.xp=0;G.growth=0;const beforeCash=G.cash');assert.equal(f.run('grantMedalReward()'),false);f.run('G.fragments=6');assert.equal(f.run('grantMedalReward()'),true);assert.equal(f.run('G.cash'),f.run('beforeCash')+300);assert.equal(f.run('G.xp'),3);assert.equal(f.run('G.medalRewardClaimed'),true);assert.equal(f.run('G.campaign.introSolved'),false);assert.equal(f.run('G.actDone||false'),false);assert.equal(f.run('grantMedalReward()'),false);assert.equal(f.run('G.cash'),f.run('beforeCash')+300);
});
await test('Completed old saves receive the medal bonus once; reload and recovered medals do not repay',f=>{
 f.run('seed("campus");G.fragments=8;delete G.medalRewardClaimed;migrate();const beforeCash=G.cash;grantMedalReward();G=JSON.parse(JSON.stringify(G));migrate();G.fragments=5');assert.equal(f.run('grantMedalReward()'),false);f.run('G.fragments=6');assert.equal(f.run('grantMedalReward()'),false);assert.equal(f.run('G.cash'),f.run('beforeCash')+300);assert.equal(f.run('G.xp'),3);
});
await test('A code-selected optional medal survives canonical fallback without becoming core evidence',async f=>{
 await prepared(f);f.run('G.fragments=5;G._fragMax=5;G.xp=0;G.site.rooms[0].fragment=true;Math.random=()=>0;const sealed=G.site.mystery.sealed;const beforeCash=G.cash');await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.fragments'),6);assert.equal(f.run('G.site.rooms[0].fragTaken'),true);assert.equal(f.run('G.evidence.length'),1);assert.equal(f.run('G.evidence[0].text'),candidate.evidence[0].text);assert.equal(f.run('G.site.mystery.sealed'),f.run('sealed'));assert.equal(f.run('G.cash'),f.run('beforeCash')+300);f.run('fragXpCheck();grantMedalReward()');assert.equal(f.run('G.xp'),4);await f.run("aiTurn('입구를 다시 조사한다')");assert.equal(f.run('G.fragments'),6);assert.equal(f.run('G.cash'),f.run('beforeCash')+300);
});
await test('Dark and story-only actions cannot acquire optional medals from forged narrative or effects',async f=>{
 await prepared(f);f.run('G.fragments=0;G.site.rooms[0].fragment=true;Math.random=()=>0;G.battery=0;G.textUse=0;callAI=async(sys)=>JSON.stringify(sys.includes("본문 일치 검토자")?{valid:true,issues:[]}:{narration:"기념 메달 조각을 발견하고 손에 넣었다.",choices:[],effects:{메달조각:true}})');await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.fragments'),0);f.run('G.battery=6;G.textUse=0;pend("",{storyOnly:true})');await f.run("aiTurn('입구를 조사한다')");assert.equal(f.run('G.fragments'),0);assert.equal(f.run('G.site.rooms[0].fragTaken||false'),false);
 f.run('callAI=async(sys)=>JSON.stringify(sys.includes("본문 일치 검토자")?{valid:true,issues:[]}:{narration:"너는 조용히 기다린다.",choices:[],effects:{items_add:[{name:"기념 메달 조각",key:true}],메달조각:true}})');await f.run("aiTurn('조용히 기다린다')");assert.equal(f.run('G.fragments'),0);assert.ok(!f.obj('G.items').includes('기념 메달 조각'));
});
await test('Both medal and old emblem effect labels are compatible while public UI uses medals',f=>{
 assert.equal(f.run('koEffects({메달조각:true}).fragment'),true);assert.equal(f.run('koEffects({교표조각:true}).fragment'),true);assert.equal(f.run('fragFoundIn("기념 메달 조각을 발견하고 손에 넣었다.")'),true);assert.equal(f.run('fragFoundIn("기념 메달 조각을 발견한 줄 알았지만 가짜였다.")'),false);assert.ok(!html.includes('교표 조각'));assert.ok(html.includes('6개 완성 보상: 캐시'));
});
console.log(`${count} private-mystery scenario groups passed.`);
})().catch(e=>{console.error(e);process.exitCode=1});
